name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: learndevopskills/mongodb:v1 # docker build -t learndevopskills/mongodv:4.0.0
    container_name: mongodb #docker run -d learndevopskills/mongodv:4.0.0
    volumes:
      - mongodb:/data/db #mongodb will stores the mongodb data in /data/db directory
  mysql:
    build: ./mysql
    image: learndevopskills/mysql:v1
    container_name: mysql
    command: --innodb-lock_wait_timeout=120
    environment:
      MYSQL_ROOT_PASSWORD: "RoboShop@1"
    volumes:
      - mysql:/var/lib/mysql
  
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  
  redis:
    image: redis:7
    container_name: redis  #docker run -d --name redis --network roboshop redis:7


  catalogue:
    build: ./catalogue
    image: learndevopskills/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  
  user:
    build: ./user
    image: learndevopskills/user:v1
    container_name: user
    depends_on:
      - redis
      - mongodb
    environment:
      MONGO: true
      REDIS_URL: 'redis://redis:6379'
      MONGO_URL: "mongodb://mongodb:27017/users"
 
  
  cart:
    build: ./cart
    image: learndevopskills/cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      CATALOGUE_PORT: 8080
    
  shipping:
    build: ./shipping
    image: learndevopskills/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
    environment:
      CART_ENDPOINT: "cart:8080"
      DB_HOST: mysql
  
  payment:
    build: ./payment
    image: learndevopskills/payment:v1
    container_name: payment
    depends_on:
      - cart
      - user
      - rabbitmq
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123

  frontend:
    build: ./frontend
    image: learndevopskills/frontend:v1
    container_name: frontend
    depends_on:
      - catalogue
    ports:
      - "80:80"

volumes:
  mongodb: # docker volume create mongodb
  mysql: 
  rabbitmq:
  redis:

networks:
  default: #which means all the services in the yaml file will use same network
    name: roboshop
    driver: bridge
    external: false